import "./globals.css";
import { Inter } from "next/font/google";
import { pacifico, poppins } from "./lib/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ehtisham UL Hassan - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${poppins.className} overflow-x-hidden dark:bg-gray-900`}>
        {children}
      </body>
    </html>
  );
}
