import './globals.css'
import { Inter } from 'next/font/google'
import { pacifico, poppins } from './lib/fonts'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} overflow-x-hidden`}>{children}</body>
    </html>
  )
}
